### ISSUE TITLE
ANNOYANCE: "Utility layer" load time

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#30]
Almost exactly 2 minutes load time on .27 and >4 minutes on .75/32 (still running as of this issue report).
this happened in a previous update.
8:20 am 5-28-20
server seems to be locked up too

**Comment by azithinkiam** [comment]
clarification: it's not the utilities layer that's taking a long time to load...that's just the last layer alphabetically so it's the last status message you see when the project loads.  no changes were made to the DB at all, so any delay is likely server-related.  the last time this occurred, the server was effectively out of memory (RAM) so that seems to be the most likely cause.  will continue investigating...
