### ISSUE TITLE
(PENDING) | (NWP) | REQUEST: move map_bk_lot in all search forms

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#31]
see attached pdf for instructions
[search-error2.pdf](https://github.com/azithinkiam/brsgis_plugin/files/4697556/search-error2.pdf)
.

**Comment by azithinkiam** [comment]
the only way to do this is to drop and re-create the columns in your preferred order for each table in the database.  since the "search" isn't really an attribute form, we can't use a custom form or the attribute table, so the custom order set there does not translate/apply.  if you really want to do this, i'll need you to provide the exact ordering from top to bottom for each layer you want to search.  check your sheet and let me know when it's in the order you want.

**Comment by Cadmanick** [comment]
"Z:\0 - Settings\Equipment\GIS\BRS_db\BRS_availableFields_for_search.xlsx" is updated for application of order of search fields.

**Comment by azithinkiam** [comment]
in order to make this change, i will need to completely drop and re-create the affected tables.  please confirm this is what you want me to do.

**Comment by azithinkiam** [comment]
Completely destroy, re-create and repopulate with data.


QGIS sets the order based on how the columns appear in the DB.

 

The DB column order cannot be changed…it’s set when the table is created…so the only way to change it is to completely re-create it from scratch…then pull the data back in.

 

It’s possible, it’s just destructive and I know how weird you are about your data.  Just looking for justification that this is really something you need to do…we can hide all the columns you don’t need to search on, but changing the order is a pretty big deal.  


Just another limitation of this platform…it is what it is.

**Comment by Cadmanick** [comment]
ok!  that's what i needed to know.  lets close this issue then.  I'll live with it, until, if ever, we go to a BRSGIS app rewrite.
