### ISSUE TITLE
(PENDING) | (NWP) | ISSUE: edit plan (???)

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#39]
error when editing la_plan
![image](https://user-images.githubusercontent.com/1892068/87432790-7243ff00-c5b6-11ea-9c7f-997b9c7dcfdb.png)

**Comment by Cadmanick** [comment]
when having anything else already selected.

**Comment by azithinkiam** [comment]
TEST reply direct from e-mail:

 



 

Apparently nothing is selected on the plans layer…only on another layer.  You’ll need to clear any selections and then step through the edit process.  

This code hasn’t changed in well over a year.  What exactly are you reporting / asking for on this one?

**Comment by azithinkiam** [comment]
not enough information provided to do anything with this.  the "error" is valid because there is no selection.  if you can provide the number of the plan you're trying to edit, i can attempt to reproduce, but there is no indication of a problem in the screenshot other than the fact that there is no plan selected, which is why it throws an exception.  unable to proceed at this time.  pending NWP.
