### ISSUE TITLE
(PENDING) | (NWP) | ISSUE: MY FLOOD LAYERS KEEP GETTING TURNED OFF...

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#46]
PLEASE FIX

**Comment by azithinkiam** [comment]
please provide useful information.  which layer(s)?  what are you doing right before this happens?  i believe mapView and siteMap are the only actions that turn layers on or off, so are you getting an error trying to generate one of those?

you provided absolutely nothing i can use to troubleshoot.  work with me here.

**Comment by Cadmanick** [comment]
I think your saved qgs file has them off... Every time you do work they return to me in the off state.

**Comment by azithinkiam** [comment]
I don’t have a saved QGS file, I use yours and I haven’t touched it all week.  You still haven’t told me which layer(s) you’re talking about.

**Comment by Cadmanick** [comment]
![image](https://user-images.githubusercontent.com/1892068/89723236-97fbd280-d9c1-11ea-92d6-0349167d666b.png)
this

**Comment by azithinkiam** [comment]
Those are turned on and off when printing mapView based on the logic you provided for the various types.

 

Have you printed mapView from your machine?  

 

Is someone else using your QGS file?  

 

Are all five of those layers supposed to be checked or only certain ones?  

 

It’s almost a week later and we’re just now getting to the information I need to be able to troubleshoot this for you.  

Please try to take the time to provide the information needed, rather than just shooting off in ALL CAPS telling me SoMeTHiNG DoESn’T WoRK.  It’s very likely this could have been completely addressed by now if you’d have just done this in the first place.

**Comment by azithinkiam** [comment]
CORRECTION: 

 

We turn the ‘FEMA’ group off at the end of SiteMap generation.  I honestly don’t remember why, but here’s the code:

 

self.toggleLayer('USA_Topo_Maps', 0)
QgsProject.instance().layerTreeRoot().findGroup('FEMA').setItemVisibilityChecked(0)

 

I honestly don’t remember why this is like this.  We turn the ‘USA Topo Maps’ layer off on purpose because that’s only used for the SiteMap, but I have no idea why we’re turning ‘FEMA’ off there, too.  I can remove that line and it won’t touch that layer group…but since I don’t remember why it’s being turned off in the first place, that might screw something else up. 

 

Let me know what you want to do on this…but to be clear, the only way these should get ‘turned off’ is via SiteMap generation…that’s literally the only place ‘FEMA’ is referenced in code in the entire plugin.

**Comment by Cadmanick** [comment]
yea i don't want fema to show in site maps... so that should stay... i'll keep my eye on it to see if i can figure it out.
do you turn it back on afterwards?
standby

**Comment by azithinkiam** [comment]
believe issue to be resolved.
