### ISSUE TITLE
(PENDING) | (NWP) | ISSUE: 3.14

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#50]
new job creation:
upon initiation tool goes to pan instead of select.
then crash.
![image](https://user-images.githubusercontent.com/1892068/91039213-23887c80-e5da-11ea-866e-a26e006f9bd4.png)
but moves on.

but populates with old job's details.

![image](https://user-images.githubusercontent.com/1892068/91039283-4ca90d00-e5da-11ea-910e-f784d8a3b9a1.png)

upon cancellation of job i get this:
![image](https://user-images.githubusercontent.com/1892068/91039316-5cc0ec80-e5da-11ea-8d94-ebca4b303d64.png)

selected yes; rollback.

samething when i close and re-open.

![image](https://user-images.githubusercontent.com/1892068/91040271-ed4bfc80-e5db-11ea-99c2-d8ed45488495.png)

we have lots of jobs to setup this week... can you fix this STAT?

**Comment by azithinkiam** [comment]
Which machine?

**Comment by azithinkiam** [comment]
Go back to 3.2.3 – there’s a folder called OLD_QGIS on the desktop with those shortcuts in it.  

 

Apparently 3.14 doesn’t work after all.  I thought you had done a little more testing with it…

**Comment by azithinkiam** [comment]
If the shortcuts for OLD_QGIS aren’t on every machine, they’re all saved here:

 

\\192.168.1.101\z\LeightonProjects\0 - Settings\GIS\QGIS\shortcuts.PRD\OLD QGIS

**Comment by azithinkiam** [comment]
3.14 has changed several things that have broken our plugin.  i believe i have it updated to handle these changes and DEV/.25 has been updated with the "fixed" version.  this is still connected to your DEV database, so please test as much functionality as you need to in order to feel comfortable before we move back in PRD.  i have tested everything i can from my end and all seems to be working as expected.  NOTE: if you get any exceptions or errors, you must stop, exit, and relaunch QGIS just to be safe.  we don't want to conflate any issues, so a 'reset' is always a best practice after an issue.  i await your feedback...

**Comment by azithinkiam** [comment]
3.14 has been abandoned for the time being.
