### ISSUE TITLE
folder face label

### ISSUE THREAD

**Issue by Cadmanick** [azithinkiam/brsgis_plugin#60]
i thought we were adding an exception to remove the redundancy as shown in this file...
i.e. we dont' need to say care of a person if the person is already listed above?

could you check to see if they are dupe and not include on line below if so?

[20-411_FolderFaceLabel_2020.10.15.xlsx](https://github.com/azithinkiam/brsgis_plugin/files/5392375/20-411_FolderFaceLabel_2020.10.15.xlsx)

**Comment by azithinkiam** [comment]
We can add another duplicate check to prevent this, but I think it uncovered another potential issue.

 

To date, we’ve had Primary_Contact  set by client rather than folder contact.  I think we need to change this over to the folder contact now that we’re potentially adding that extra line.  

 

I’m pulling your DB now and will have something worked up shortly to review…shouldn’t be a huge deal.

**Comment by azithinkiam** [comment]
This one is a little confusing and I’m not sure if it’s because of how she’s entered the contacts or my logic…after updating, this is what I have:

 


Pendleton-F/K/A Brown, Lucille

FOLDER Contact \ ContactName


Cusumano, Shaun & Sarah

CLIENT Contact \ ContactName

 	

c/o: Pendleton, Lucille

FOLDER Contact \ Primary Contact

 	

 

Logic is:

 

ws['A1'] = folderName
if str(folderName) != str(clientName):
    ws['A2'] = clientName
    if str(clientName) != str(primaryContact):
        ws['A3'] = 'c/o: ' + primaryContact
    else:
        ws['A3'] = ''
else:
    ws['A3'] = ''

 

 

folderName will always be TOP – cell A1

 

if folderName is different than ClientName, put clientName in A2

 

if clientName in A2 is different than FOLDER primary contact, put primaryContact in A3 as c/o

 

So…if clientName and folderName are the same, only A1 gets the folderName and nothing else is populated.

 

--

 

So, for this particular job, how would you prefer it be displayed?

**Comment by azithinkiam** [comment]
changes made per request.
